on: 
  workflow_dispatch: 
    inputs:
      name:
        description: 'GCR image microservice name like gintaa-user'
        required: true
        default: 'gintaa-user'
      date:
        description: 'Specify the date from which you want to delete'
        required: true
        default: '2021-09-01'  

name: GCR Image Deletion

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_POC }}
  

jobs:
   build:
     name: GCR Image deletion     
     runs-on: ubuntu-latest
     steps:
       - name: 'Authenticate to Gcloud'
         uses: google-github-actions/setup-gcloud@master
         with:
           project_id: ${{ env.PROJECT_ID }}
           # service_account_email: myServiceAccount@myProject.iam.gserviceaccount.com
           service_account_key: ${{ secrets.GCP_SA_KEY_POC }}
           export_default_credentials: true
       - name: 'Cleanup GCR images'
         run: |
             echo "IMAGE_name=gcr.io/${{ env.PROJECT_ID }}/${{ github.event.inputs.name }}"
             echo "DELETE_BEFORE=${{ github.event.inputs.date }}"
             for digest in $(gcloud container images list-tags \
               gcr.io/${{ env.PROJECT_ID }}/${{ github.event.inputs.name }} --limit=999999 \
               --filter='(-tags=latest AND -tags~dirty) OR timestamp.datetime < ${{ github.event.inputs.date}}' \
               --format='get(digest)' )  
             do
                 gcloud container images delete "gcr.io/${{ env.PROJECT_ID }}/${{ github.event.inputs.name}}@${digest}" --quiet --force-delete-tags
             done
