on: 
  workflow_dispatch: 
    inputs:
      name:
        description: 'GCR image microservice name like gintaa-user'
        required: true
        default: 'gintaa-user'

name: GCR Image Add Tag - beta

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_POC }}
  

jobs:
   build:
     name: GCR Image Add Tag    
     runs-on: ubuntu-latest
     steps:
#        - name: Get file service-template
#          run: |-
#             export SERVICE_TEMPLATE="$(curl -H 'Authorization: token ${{ secrets.TEST_GITHUB_TOKEN }}' \
#             -H 'Accept: application/vnd.github.v4.raw' \
#             -L https://api.github.com/repos/asconsoft/gintaa-otp/charts/gintaa-otp/Chart.yaml)"
#             echo $SERVICE_TEMPLATE
       - name: get file
         env:
          TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
         run: |
          export SERVICE_TEMPLATE="$(curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/asconsoft/gintaa-otp/main/charts/gintaa-otp/Chart.yaml)"
          echo $SERVICE_TEMPLATE
