on: 
  workflow_dispatch: 
  #needs: [CI, Build_myApp]
    inputs:
      foo:
        description: 'GCR image microservice name like gintaa-user'
        required: true
        default: 'gintaa-user'

jobs:
   build:
     name: GCR Image deletion     
     runs-on: ubuntu-latest
     steps:
       - name: 'Authenticate to Gcloud'
         uses: google-github-actions/setup-gcloud@master
         with:
           project_id: myProject
           service_account_email: myServiceAccount@myProject.iam.gserviceaccount.com
           service_account_key: ${{ secrets.CONTAINER_ADMIN_NP_SA }}
           export_default_credentials: true
       - name: 'Cleanup untagged images in nonprod'
         run: gcloud container images list-tags gcr.io/gintaa-cloud-poc/${{inputs.foo}} --filter='-tags:*' --format="get(digest)" --limit=10 > tags && while read p; 
              do gcloud container images delete "gcr.io/myProject/myApp@$p" --quiet; done < tags
