on: 
  workflow_dispatch: 
    inputs:
      foo:
        description: 'GCR image microservice name like gintaa-user'
        required: true
        default: 'gintaa-user'

jobs:
   build:
     name: GCR Image deletion     
     runs-on: ubuntu-latest
     steps:
       - name: 'Authenticate to Gcloud'
         uses: google-github-actions/setup-gcloud@master
         with:
           project_id: gintaa-cloud-poc
           # service_account_email: myServiceAccount@myProject.iam.gserviceaccount.com
           service_account_key: ${{ secrets.GCP_SA_KEY_POC }}
           export_default_credentials: true
       - name: 'Cleanup GCR images'
         run: |
             echo "IMAGE=gcr.io/gintaa-cloud-poc/${{inputs.foo}}"
             echo "DELETE_BEFORE=2021-09-01"
             for digest in $(gcloud container images list-tags \
             gcr.io/gintaa-cloud-poc/${{inputs.foo}} --limit=999999 \
               --sort-by=TIMESTAMP \
               --filter="timestamp.datetime &lt; '${DELETE_BEFORE}'" \
               --format='get(digest)'; do
                # gcloud container images delete -q --force-delete-tags "${IMAGE}@${digest}"
                gcloud container images delete "gcr.io/gintaa-cloud-poc/${{inputs.foo}}@${digest}" --quiet
               done
