on: 
  workflow_dispatch: 
    inputs:
      name:
        description: 'GCR image microservice name like gintaa-user'
        required: true
        default: 'gintaa-user'
      date:
        description: 'Specify the date from which you want to delete'
        required: true
        default: '01-09-2021'  
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_POC }}
  

jobs:
   build:
     name: GCR Image deletion     
     runs-on: ubuntu-latest
     steps:
       - name: 'Authenticate to Gcloud'
         uses: google-github-actions/setup-gcloud@master
         with:
           project_id: ${{ env.PROJECT_ID }}
           # service_account_email: myServiceAccount@myProject.iam.gserviceaccount.com
           service_account_key: ${{ secrets.GCP_SA_KEY_POC }}
           export_default_credentials: true
       - name: 'Cleanup GCR images'
         run: |
             echo "IMAGE_name=gcr.io/${{ env.PROJECT_ID }}/${{ inputs.name }}"
             echo "DELETE_BEFORE=${{ inputs.date }}"
             for digest in $(gcloud container images list-tags \
               gcr.io/${{ env.PROJECT_ID }}/${{inputs.name}} --limit=999999 \
               --sort-by=TIMESTAMP \
               --filter='timestamp.datetime > ${{inputs.date}}' \
               --format='get(digest)'; do
                 gcloud container images delete "gcr.io/${{ env.PROJECT_ID }}/${{inputs.name}}@${digest}" --quiet
             done
