on:
  push:
    branches:
      - develop
      - feature/zap

name: Release | Deploy

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.gintaa.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  firebase_deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        run: echo "Deploy to firebase"
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: '#test'
          mention: 'here'
          if_mention: failure,cancelled
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,ref,author,took
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
