on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Enter website URL'
        required: true
        default: 'https://beta.gintaa.com/'

name: ZAP SCAN

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ github.event.inputs.target }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
